### ISSUE TITLE
Mettle Testing Framework

### ISSUE THREAD

**Issue by michaelherndon** [nerdymishka/home-lab#1]
Extend xunit.net to create a testing workflow in .NET that suites my ideal testing style.  Mettle already exists in my other projects. The goal is to enhance the code as it is imported. It should support .NETStandard2.1

 - [ ] Enable dependency injection using only IServiceProvider for constructor injection in test classes and method injection in test cases.
 - [ ] Provide an extensible interface for Assert as IAssert. 
 - [ ] Enable xunit.net 3 asserts for span/memory.
 - [ ] Allow IAssert to be injected into constructors and methods.
 - [ ] Allow ITestOutputHelper to be injected into constructors and methods.
 - [ ] Add custom test attributes that can inject traits such as the default category, tags, links to tickets, etc.
 - [ ] Support conditional tests similar to dotnet/arcade's extensions to xunit.
